#!/usr/bin/env bash
declare -A options=(
    ["Lock"]="hyprlock"
    ["Log Out"]="hyprctl dispatch exit"
    ["Reboot"]="reboot"
    ["Shutdown"]="shutdown now"
)

input=$(printf '%s\n' "${!options[@]}" | rofi -i -dmenu -p "Power")
[ -n "${options[${input}]}" ] && eval "${options[${input}]}" 
