#!/usr/bin/env bash
declare -A OPTIONS=(
    ["Lock"]="hyprlock"
    ["Log Out"]="hyprctl dispatch exit"
    ["Reboot"]="reboot"
    ["Shutdown"]="shutdown now"
)

input=$(printf '%s\n' "${!OPTIONS[@]}" | rofi -i -dmenu -p "Power")
[ -n "${OPTIONS[${input}]}" ] && eval "${OPTIONS[${input}]}" 
