#!/usr/bin/env bash
function aws-profile-export() {
    i=0
    while read -r LINE; do
        echo "${LINE} $i 'send-keys export\ AWS_PROFILE=${LINE}'"
        i=$((i + 1))
    done <<< "$(grep "^\[profile" "$HOME/.aws/config" | sed 's/\[profile \([^]]*\)\]/\1/')"
}

aws-profile-export | xargs tmux display-menu -T "Profile"
