#!/usr/bin/env bash
function session() {
    local path="${1%/}"
    [[ "${path}" != /* ]] && path="${PWD}/${path}"
    if [[ ! -d "${path}" ]]; then
        echo "${path} is not a directory" 1>&2
        return 1
    fi

    local session="${2:-${path##*/}}"

    if ! tmux has-session -t "${session}" 2> /dev/null; then
        tmux new-session -d -s "${session}" -c "${path}" -n "Home" || return 1
    fi

    local action
    if [[ -z "${TMUX}" ]]; then
        action="attach-session"
    else
        action="switch-client"
    fi
    tmux "${action}" -t "${session}:1" || return 1
    return 0
}

if [[ $# -eq 0 ]]; then
    session "${HOME}" "Home"
    exit $?
fi
for path in "${@}"; do
    session "${path}" || exit $?
done

# TODO: Fix `tcd ~` (and other explicit variants) to behave the same as `tcd`
