#!/usr/bin/env bash

# This script takes a path as an optional argument.
# If no argument is provided, it defaults to the home directory.
# It will determine the bottom directory of the path and attach to that session.
# If the session does not exist, it will create a new tmux session with that name and path.
if [ -z "${1}" ]
then
    FILEPATH="${HOME}"
    SESSION_NAME="Home"
else
    if [[ $1 == */ ]]; then
        FILEPATH="$PWD/${1:0:${#1}-1}"
    else
        FILEPATH="$PWD/$1"
    fi
    SESSION_NAME="${FILEPATH##*/}"
fi

if [ ! "$(tmux has-session -t "${SESSION_NAME}")" ]
then
    tmux new-session -d -s "${SESSION_NAME}" -c "${FILEPATH}" -n "Home"
fi

if [ -z "${TMUX}" ]
then
    tmux attach-session -t "${SESSION_NAME}:1"
else
    tmux switch-client -t "${SESSION_NAME}:1"
fi
