#!/usr/bin/env bash
function session() {
    local path session
    path="$( cd "${1}" && pwd )" || return 1
    if [[ "${path}" == "${HOME}" ]]; then
        session="Home"
    else
        session="${path##*/}"
    fi

    if ! tmux has-session -t "${session}" 2> /dev/null; then
        tmux new-session -d -s "${session}" -c "${path}" -n "Home" || return 1
    fi

    local action
    if [[ -z "${TMUX}" ]]; then
        action="attach-session"
    else
        action="switch-client"
    fi
    tmux "${action}" -t "${session}:1" || return 1
    return 0
}

if [[ $# -eq 0 ]]; then
    session "${HOME}"
    exit $?
fi
for path in "${@}"; do
    session "${path}" || exit $?
done

# TODO: Support `/` (maybe)
