#!/usr/bin/env bash
function open-ticket() {
    local JIRA_URL="https://keyloop.atlassian.net"
    local TICKET_ID="$1"
    if [[ -z "${TICKET_ID}" ]]; then
        echo "Usage: ticket <ticket-id>"
        return 1
    fi
    if [[ "${TICKET_ID}" =~ ^[0-9] ]]; then
        URL="${JIRA_URL}/browse/MDATA-${TICKET_ID}"
    else
        URL="${JIRA_URL}/browse/${TICKET_ID}"
    fi
    ${BROWSER} "${URL}" &> /dev/null
}

alias ticket=open_ticket
