#!/usr/bin/env bash
function run-state-machine() {
    local n_args name payload
    n_args=${#}
    name="${1}"
    # TODO: Move payload to an opt & support multiple state machines?
    payload="${2}"
    if [ -z "${name}" ] || [ "${n_args}" -eq 0 ] || [ "${n_args}" -gt 2 ]; then
        echo "Usage: run-state-machine <state-machine-name-regex> [<json-payload>]"
        return 1
    fi

    local arn state_machines
    declare -a state_machines
    while read -r arn; do
        [[ "${arn}" =~ ${name} ]] && state_machines+=("${arn}")
    done < <(aws stepfunctions list-state-machines --query "stateMachines[*].[stateMachineArn]" --output text)
    declare -i count
    count=${#state_machines[@]}
    if [[ "${count}" == 0 ]]; then
        echo "No state machine found with name containing ${name}"
        return 1
    elif [[ "${count}" -gt 1 ]]; then
        echo "Multiple state machines found with name containing ${name}"
        printf '%s\n' "${state_machines[@]}"
        return 1
    fi

    local state_machine_arn execution_arn
    state_machine_arn="${state_machines[0]}"
    if [[ -z "${payload}" ]]; then
        execution_arn=${ aws stepfunctions start-execution --state-machine-arn "${state_machine_arn}" --query "executionArn" --output text; }
    else
        execution_arn=${ aws stepfunctions start-execution --state-machine-arn "${state_machine_arn}" --query "executionArn" --output text --input "${payload}"; }
    fi

    echo "STARTED ${execution_arn}"
    local execution_status
    while true; do
        execution_status=${ aws stepfunctions describe-execution --execution-arn "${execution_arn}" --query "status" --output text; }
        printf '\r' >&2
        case "${execution_status}" in
            SUCCEEDED)
                printf '%s\n' "${execution_status} ${execution_arn}"
                return 0;;
            FAILED)
                printf '%s\n' "${execution_status} ${execution_arn}"
                aws stepfunctions describe-execution --execution-arn "${execution_arn}" --query "{status:status,error:error,cause:cause}" --no-cli-pager | \
                    jq '{status: .status, error: .error, cause: (.cause as $cause | try ($cause | fromjson) catch $cause)}'
                return 1
            ;;
            *)
                printf '%s' "${execution_status} ${execution_arn}" >&2
                sleep 5;;
        esac
    done
}

alias rsm=run-state-machine
