#!/usr/bin/env bash
CONNECTED_STATES=('Connecting' 'Connected' 'Reconnecting' 'DisconnectingToReconnect')
DISCONNECTED_STATES=('Disconnected' 'Interrupted' 'Disconnecting')

STATUS=$(piactl get connectionstate)

if printf '%s\0' "${CONNECTED_STATES[@]}" | grep -Fxqz -- "${STATUS}"; then
    echo 'Disconnecting'
    piactl disconnect
    exit 1
fi

if printf '%s\0' "${DISCONNECTED_STATES[@]}" | grep -Fxqz -- "${STATUS}"; then
    echo 'Connecting'
    piactl connect
    exit 1
fi

echo "Unknown STATUS ${STATUS}"
exit 0
