#!/usr/bin/env bash
SCRIPT_DIR="${HOME}/.config/rofi/scripts"
NETFLIX="Netflix"
PRIME_VIDEO="Amazon Prime Video"
declare -A sites=(
    ["Chess"]="www.chess.com"
    ["Disney+"]="www.disneyplus.com"
    ["Github"]="www.github.com/ChrisPJohnstone"
    ["GMail"]="mail.google.com"
    ["LinkedIn"]="www.linkedin.com"
    ["${NETFLIX}"]="www.netflix.com"
    ["Outlook"]="outlook.live.com"
    ["${PRIME_VIDEO}"]="www.amazon.co.uk/gp/video/storefront/"
    ["Reddit"]="www.reddit.com"
    ["Teams"]="teams.live.com"
)
declare -A follow_ups=(
    ["${NETFLIX}"]="${SCRIPT_DIR}/browser/search_netflix"
    ["${PRIME_VIDEO}"]="${SCRIPT_DIR}/browser/search_prime_video"
)

input=$(printf '%s\n' "${!sites[@]}" | rofi -i -dmenu -p "Browse")
if [[ -z ${input} ]]; then
    exit "Escape"
elif [[ -z "${sites[${input}]}" ]]; then
    ${SCRIPT_DIR}/browser/search_ddg $1 "${input}"
elif [[ -n "${follow_ups[${input}]}" ]]; then
    secondary_input=$(${SCRIPT_DIR}/input ${input})
    eval "${follow_ups[${input}]} $1 \"${secondary_input}\""
else
    $1 "${sites[${input}]}"
fi
