" Aesthetic Choices
colorscheme slate
highlight VertSplit ctermbg=None

" Enable syntax highlighting
syntax on

" Syntax corrections for unsupported file types
augroup SyntaxHighlighting
    autocmd!
    autocmd BufNewFile,BufRead *.md set filetype=text
    autocmd BufNewFile,BufRead *.q set filetype=sql
augroup END

" Display line number & highlight line cursor is on
set scrolloff=100
set number
augroup RelativeNumberToggle
    autocmd!
    autocmd BufEnter,FocusGained,WinEnter * if &number | set relativenumber | endif
    autocmd BufLeave,FocusLost,WinLeave   * if &number | set norelativenumber | endif
augroup END

" Always show status bar
set laststatus=2
set statusline=[%f]\ %y\ %=\ [Column:\ %v]

" Set tab length & use spaces
set expandtab
set smartindent
set shiftwidth=4
set tabstop=4

" Window resizing using Ctrl + hjkl
nnoremap <C-W><C-h> <C-W><
nnoremap <C-W><C-j> <C-W>+
nnoremap <C-W><C-k> <C-W>-
nnoremap <C-W><C-l> <C-W>>

" Highlight matches while searching
set hlsearch

" Tabable options when autocompleting in command mode
" set wildmenu
set wildmode=longest

" For all those times you hit a button and you're not sure what it was
set showcmd

" Enable backspacing to previous line
set backspace=eol,start

" Disable that gahd damn bell
set visualbell

" Disable linewrapping
set nowrap

" Enables gf to open python imports
filetype plugin on

" Add recursive subdirectories to path
set path+=**

" Remove directories from vimgrep
set wildignore+=*/__pycache__/*
set wildignore+=*venv/*
set wildignore+=*/node_modules/*

" Set leader key to space
let mapleader = " "

" Save shorcut
noremap <leader>s :w<CR>
