#!/usr/bin/env bash

# Ignore case for tab completion
bind 'set completion-ignore-case on'

# Treat `-` and `_` as equivalent for tab completion
bind 'set completion-map-case on'

# Color the common prefix when listing completions
bind 'set colored-completion-prefix on'

# Color files based on type
bind 'set colored-stats on'

# Have completion suggestions output on seperate rows
bind 'set completion-display-width 0'
