#!/usr/bin/env bash
function completion_cdk() {
    COMPREPLY=()

    local CUR_WORD ARGS OPTIONS STACKS
    CUR_WORD="${COMP_WORDS[COMP_CWORD]}"
    ARGS=("${COMP_WORDS[@]}")

    OPTIONS=$(cdk --get-yargs-completions "${ARGS[@]}")
    STACKS=$(ls cdk.out/${COMP_WORDS[COMP_CWORD]}*.template.json 2> /dev/null | sed 's/cdk.out\/\(.*\)\.template\.json/\1/')
    if [[ "${ARGS[*]}" =~ deploy|destroy ]]; then
        COMBINED=("${OPTIONS} ${STACKS}")
        COMPREPLY+=( $(compgen -W "${COMBINED}" -- "${CUR_WORD}") )
        return 0
    else
        COMPREPLY=( $(compgen -W "${OPTIONS}" -- "${CUR_WORD}") )
        return 0
    fi
}

complete -F completion_cdk cdk
