#!/usr/bin/env bash
if [[ "$(uname)" == "Linux" ]]; then
    complete -C /usr/bin/terraform terraform
elif [[ "$(uname)" == "Darwin" ]]; then
    complete -C terraform terraform
    # TODO: Fix this for MacOS
fi
