#!/usr/bin/env bash
if [[ "$(uname)" == "Linux" ]]; then
    complete -C /usr/bin/terraform terraform
elif [[ "$(uname)" == "Darwin" ]]; then
    complete -C /opt/homebrew/Cellar/tfenv/3.0.0/versions/1.11.2/terraform terraform
fi
