#!/usr/bin/env bash
if [[ "$(uname)" == "Linux" ]]; then
    export BROWSER='firefox'
elif [[ "$(uname)" == "Darwin" ]]; then
    export BROWSER='open -u'
else
    echo "Unknown OS, please set BROWSER manually or update bashrc"
fi
