require("plugins.mason")

require("plugins.diffview")
require("plugins.fugitive")
require("plugins.mini-comment")
require("plugins.mini-hipatterns")
require("plugins.mini-surround")
require("plugins.mini-trailspace")
require("plugins.oil")
require("plugins.showkeys")
require("plugins.telescope")
require("plugins.tokyonight")
require("plugins.treesitter")
